version = "0.1"
date = "07 November 2014"
package = "calibration"
title = "Goodness of Fit"
url = "http://www.terrame.org"
authors = "Antonio Oliveira, Pedro Andrade, Raian"
contact = "junior092006@hotmail.com, pedro.andrade@inpe.br"